"""Build /workspace/submission/portfolio.py from the offline cache: configs scored on all 5 seeds, ranked by a robust
statistic (mean + 0.5*max deviation), de-duplicated; K entries."""
import json, sys, numpy as np
sys.path.insert(0, '/workspace/dev')
from harness import load_cache
K = int(sys.argv[1]) if len(sys.argv) > 1 else 30
cache = load_cache(); by = {}
for r in cache.values():
    if list(r['origins']) != [8227, 10284, 12341]: continue
    k = json.dumps(r['cfg'], sort_keys=True, default=str); by.setdefault(k, {})[r['seed']] = float(np.mean(r['per']))
rows = []
for k, d in by.items():
    if all(sd in d for sd in range(5)):
        v = np.array([d[sd] for sd in range(5)])
        if not np.all(np.isfinite(v)): continue
        rows.append((v.mean() + 0.5 * (v.max() - v.mean()), v.mean(), v.std(), json.loads(k)))
rows.sort(key=lambda x: x[0])
# diversity: at most 2 variants per (layers, spectral_radius) family, best first
seen = {}; chosen = []
for row in rows:
    fam = (tuple(row[3]['layers']), row[3]['spectral_radius'])
    if seen.get(fam, 0) >= 2: continue
    seen[fam] = seen.get(fam, 0) + 1; chosen.append(row)
    if len(chosen) >= K: break
def norm(c):
    c = dict(c)
    if isinstance(c.get('layers'), list): c['layers'] = tuple(int(x) for x in c['layers'])
    if isinstance(c.get('leak'), list): c['leak'] = tuple(float(x) for x in c['leak'])
    if 'voltage' in c.get('input_scale', {}) and not c.get('voltage_feedback', True): c['input_scale'] = {a: b for a, b in c['input_scale'].items() if a != 'voltage'}
    return c
with open('/workspace/submission/portfolio.py', 'w') as fh:
    fh.write('"""Portfolio of designs found offline with the evaluator protocol (3 dev origins), all scored on seeds 0-4.\n'
             'Ordered by robust dev score (5-seed mean + half the worst-seed excess). Generated by /workspace/dev/make_portfolio.py."""\n')
    fh.write('PORTFOLIO = [\n')
    for rob, m, sd, c in chosen:
        fh.write(f'    # robust {rob:.4f}  mean {m:.4f}  sd {sd:.4f}\n    {norm(c)!r},\n')
    fh.write(']\n')
for rob, m, sd, c in chosen: print(f'{rob:.4f} {m:.4f} {sd:.4f} {c["layers"]} inter={c.get("inter_scale")} sr={c["spectral_radius"]} leak={c["leak"]}')
print(len(rows), 'configs had 5 seeds')
